bt-53: Create sidebar
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #114
Opened 2023-08-25 16:37 UTC by vladjsp

![sidebar2](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/8f010956-7396-4b3e-8447-45d8f7887c82)

2023-08-25 17:11 UTC, JemiJe commented
I saw prev commit, but maybe we should leave ability to pass `menuItems` via props, but leave default items and add passed using, for example `menuItems = menuItems.concat(extraItems)`. As I see it, better to make component more extensible.

2023-08-25 17:34 UTC, savinaDaria approved these changes

2023-08-26 10:42 UTC, nikita-remeslov requested changes
In general looks good

2023-08-26 10:42 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/sidebar/sidebar.tsx
> +            <div className={styles.logo}></div>
Leave some comment, that we should update it after we will have our logo

2023-08-26 10:42 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/sidebar/sidebar.tsx
you should import it to the root components.ts file

2023-08-26 19:04 UTC, Simpsonkk commented
Probably also we can use  z-index: 1 in .wrapper because the sidebar is always located above the header component

2023-08-28 06:36 UTC, nikita-remeslov approved these changes

2023-08-28 06:36 UTC, merged