bt-19 : Sign-in route
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #139
Opened 2023-08-28 13:27 UTC by ptarho

New PR without merged bt-86 branch

2023-08-28 16:41 UTC, nikita-remeslov requested changes

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/users/user.entity.ts
> +        passwordHash: string;
token should not be part of user entity

2023-08-28 16:41 UTC, nikita-remeslov commented on shared/src/bundles/users/types/user-find-response-dto.type.ts
> +    passwordHash: string;
hash should not be a part of response

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +        };
```suggestion
        return {
            token,
            user,
        };
```

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +            token: await tokenService.create({ id: user.id }),
```suggestion
            token,
            user,
```

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +            token: await tokenService.create({ id: user.id }),
you should return user and token

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +                message: 'User already exist.',
add to error-message.enum.ts

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +                cause: 'Email already used',
```suggestion
```

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +                status: HttpCode.CONFLICT,
should be 400 not 409

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +                cause: 'User with the given email does not exist',
```suggestion
```

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +                message: 'User not found',
add to shared

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +                message: 'Unauthorized',
add to shared

2023-08-28 16:41 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +                cause: 'Invalid credentials',
```suggestion
```

2023-08-28 17:08 UTC, nikita-remeslov commented on backend/src/bundles/users/user.service.ts
> +                passwordSalt: 'SALT', // Remove with a new migration ticket
already in the development

2023-08-28 17:08 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +            token: await tokenService.create({ id: user.id }),
```suggestion
            token,
	        user,
```

2023-08-29 08:44 UTC, nikita-remeslov commented
conflicts

2023-08-29 08:59 UTC, ptarho commented
@nikita-remeslov fixed

2023-08-29 09:05 UTC, nikita-remeslov requested changes

2023-08-29 09:05 UTC, nikita-remeslov commented on backend/src/bundles/auth/auth.service.ts
> +                status: HttpCode.CONFLICT,
```suggestion
                status: HttpCode.BAD_REQUEST,
```

2023-08-29 09:18 UTC, nikita-remeslov approved these changes

2023-08-29 10:03 UTC, MaksymGavatuk approved these changes

2023-08-29 10:04 UTC, merged

2023-08-29 10:05 UTC, Monyster approved these changes