bt-138: Modify list of white routes
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #145
Opened 2023-08-28 16:03 UTC by ptarho

I changed format of white routes list to required.
![routes](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/67747035/bdc2b633-d91a-48e0-ba1c-c388a21fda69)
Also modified helper to work with new format and used regex to handle routes like:
`/v1/documentation/static/*`
![helper](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/67747035/5d2843df-1749-4135-a86a-3f5f235b81c2)

2023-08-28 16:57 UTC, nikita-remeslov requested changes

2023-08-28 16:57 UTC, nikita-remeslov commented on backend/src/common/server-application/helpers/check-white-route.helper.ts
>  const checkWhiteRoute = (route: string, method: string): boolean => {
```suggestion
const checkWhiteRoute = ({path, method}: Params): boolean => {
```

2023-08-28 16:57 UTC, nikita-remeslov commented on backend/src/common/server-application/helpers/check-white-route.helper.ts
> +    return false;
we can make it mack simplest 

```js
  WHITE_ROUTES.some((route) => {
    return (
      route.path.test(regex) &&
      route.methods.includes(method)
    );
```

2023-08-28 16:57 UTC, nikita-remeslov commented on backend/src/common/server-application/constants/api.constants.ts
> +    },
if you want to use RegExp it should be here. 

in this case, you can combine these routes

```suggestion
    {
        path: new RegExp(`^/api/v1${APIPath.DOCUMENTATION}/*`),
        methods: ['GET'],
    },
```

2023-08-29 07:09 UTC, MaksymGavatuk approved these changes

2023-08-29 08:43 UTC, nikita-remeslov approved these changes

2023-08-29 08:43 UTC, merged