bt-86: Sign-up
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #152
Opened 2023-08-28 21:41 UTC by Monyster

Closes #86 

Check flow:

1. No body
2. Only 1 value in body
3. Invalid json format ( "," after password)
4. Validation email - wrong email
5. Validation password - not empty
6. Succesfull sign up
7. User already exist

2023-08-29 17:07 UTC, nikita-remeslov commented
@ptarho check please your part

2023-08-29 17:30 UTC, MChornomaz approved these changes

2023-08-29 19:29 UTC, ptarho requested changes

2023-08-29 19:29 UTC, ptarho commented on shared/src/bundles/users/types/user-sign-up-response-dto.type.ts
> +    role: ValueOf<typeof UserRole>;
@nikita-remeslov

2023-08-29 19:29 UTC, ptarho commented on shared/src/bundles/users/types/user-sign-up-response-dto.type.ts
> +    role: ValueOf<typeof UserRole>;
Should we leave it for now?

2023-08-29 19:39 UTC, Monyster commented on shared/src/bundles/users/types/user-sign-up-response-dto.type.ts
> +    role: ValueOf<typeof UserRole>;
I thought it need to choose a registration strategy for a new user.
But now I think that frontend already contains this.
So maybe it's useless value in response.

2023-08-30 07:57 UTC, Monyster commented
@nikita-remeslov 
Fixed conflicts.

2023-08-30 08:05 UTC, ptarho approved these changes

2023-08-30 08:09 UTC, anton-otroshchenko approved these changes

2023-08-30 09:14 UTC, Monyster commented
Fixed conflicts.

2023-08-30 09:27 UTC, nikita-remeslov approved these changes

2023-08-30 09:27 UTC, merged