bt-146: Create models for entities user details and hard skills from bt-72
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #165
Opened 2023-08-29 11:25 UTC by lavandosya

Now I've added types for select components, so you can check it. Also finished this task, but I'm waiting for Veronika's pull request to be merged because I need her changes in my PR. When Veronika finish her PR, I will commit my changes.

2023-08-29 12:12 UTC, MaksymGavatuk approved these changes

2023-08-29 15:45 UTC, nika-sirak requested changes

2023-08-29 15:45 UTC, nika-sirak commented on backend/src/bundles/users/user.model.ts
> +                from: 'users.is',
from: 'users.id',

2023-08-29 15:45 UTC, nika-sirak commented on backend/src/bundles/users/user.model.ts
> +                to: 'users_details.user_id',
user_details.user_id or user_details.userId?

2023-08-29 17:49 UTC, nikita-remeslov requested changes

2023-08-29 17:49 UTC, nikita-remeslov commented on backend/src/bundles/users/user.model.ts
> +                from: 'users.is',
not resolved

2023-08-29 17:49 UTC, nikita-remeslov commented on shared/src/bundles/users/types/employment-type.type.ts
> +    | 'Full-Time'
```suggestion
    | 'Full Time'
```

2023-08-29 17:49 UTC, nikita-remeslov commented on shared/src/bundles/users/types/employment-type.type.ts
> +    | 'Freelance(projects)'
```suggestion
    | 'Freelance/Projects'
```

2023-08-29 17:49 UTC, nikita-remeslov commented on shared/src/bundles/users/types/types.ts
> +export { type PreferredLanguages } from './preferred-languages.type.js';
better make it like enums

2023-08-29 17:49 UTC, nikita-remeslov commented on backend/src/bundles/hard-skills/hard-skills.model.ts
> +                through: {
I think we should use one style.
`hard_skill_id`

2023-08-29 17:49 UTC, nikita-remeslov commented on backend/src/bundles/hard-skills/hard-skills.model.ts
> +                through: {
Also you should make it like this
```js
            join: {
                from: `${DatabaseTableName.USERS}.id`,
                to: `${DatabaseTableName.USER_DETAILS}.user_id`,
            },
```

2023-08-29 17:49 UTC, nikita-remeslov commented on backend/src/bundles/hard-skills/hard-skills.model.ts
> +                through: {
we should snake_case everywhere

2023-08-29 18:02 UTC, lavandosya commented on backend/src/bundles/hard-skills/hard-skills.model.ts
> +                through: {
But in models we use camel case, that's why here it in camel case

2023-08-29 18:03 UTC, lavandosya commented on backend/src/bundles/users/user.model.ts
> +                from: 'users.is',
I resolved it in next commit

2023-08-29 18:10 UTC, nikita-remeslov commented on backend/src/bundles/hard-skills/hard-skills.model.ts
> +                through: {
than for tables let use snake case and for column camel case

ok?

2023-08-29 19:08 UTC, MaksymGavatuk requested changes

2023-08-29 19:08 UTC, MaksymGavatuk commented on backend/src/bundles/hard-skills/hard-skills.model.ts
> +                to: 'user_details.id',
Use DatabaseTableName enum

2023-08-30 06:43 UTC, nikita-remeslov approved these changes

2023-08-30 06:46 UTC, anton-otroshchenko approved these changes

2023-08-30 06:47 UTC, merged