bt-182: Add logo component
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #187
Opened 2023-08-30 17:05 UTC by Monyster

Closes #182 

Example code:
```
            <Logo />
            <Logo isCollapsed />
```

Result:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/e71f1a44-4e47-48d4-8f9e-347d07ab0443)

2023-08-30 17:30 UTC, vladjsp commented on frontend/src/bundles/common/components/logo/styles.module.scss
> +@import url("../../../../assets/css/styles.scss");
we don't need this import here.

2023-08-30 17:40 UTC, vladjsp commented
also seems that the big logo (67x67) has border-radius 7px and small one (48x48) has border-radius 5px

2023-08-30 17:41 UTC, nikita-remeslov requested changes

2023-08-30 17:41 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/logo/logo.tsx
> +                className={clsx(
use `getValidClassNames` helper

2023-08-30 17:41 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/logo/logo.tsx
> +    isCollapsed?: boolean;
add `className` prop to apply styles

2023-08-30 17:43 UTC, vladjsp commented
in general looks good and easy to use
`<Logo isCollapsed={true}/>`
![logo](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/5ea3e3da-a3d8-4589-907e-da17668f5f6e)

2023-08-31 10:09 UTC, nikita-remeslov approved these changes

2023-08-31 10:11 UTC, anton-otroshchenko approved these changes

2023-08-31 10:12 UTC, merged