bt-189: Not found page
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #195
Opened 2023-08-31 10:28 UTC by Monyster

```js
const NotFoundPage: React.FC<Properties> = ({ avatarUrl, isOnline }) => (
      <PageLayout avatarUrl={avatarUrl} isOnline={isOnline}>
      </PageLayout>
  );
```

2023-08-31 11:14 UTC, nikita-remeslov requested changes

2023-08-31 11:14 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/page-layout/styles.module.scss
@Monyster contact with @Simpsonkk about page layout

2023-08-31 11:14 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/page-layout/page-layout.tsx
> +    <div className={getValidClassNames(styles.pageContainer)}>
Better to use Grid component

2023-08-31 11:14 UTC, nikita-remeslov commented on frontend/src/bundles/common/pages/not-found/not-found.tsx
> +    <div className={getValidClassNames(styles.pageContainer)}>
looks like we can use Grid component

2023-08-31 14:17 UTC, Simpsonkk commented on frontend/src/bundles/common/components/page-layout/styles.module.scss
Yep, for your current layout, you don't need a page layout therefore you can remove it here.

2023-08-31 14:37 UTC, Simpsonkk commented
The page looks great on my local machine too. Why did you change the position header to sticky? I think we should use fixed but I see that you have not already used the header on your page and probably will remove this changes.

2023-08-31 15:41 UTC, Monyster commented
> The page looks great on my local machine too. Why did you change the position header to sticky? I think we should use fixed but I see that you have not already used the header on your page and probably will remove these changes.

When you use :fixed, it applies top, left, etc. to global window, but if you use :sticky, you can move it to any parent component with position:relative;
Thus, we have sidebars that cross the same level as thwe header. And we can to hide some stuffs in header.

To solve this, did next:
- The left side is the sidebar and the right side is the [container].
- The [container] has a position:relative.
- And the header is aligned inside this [container] without hiding behind the sidebar.

and when you pass child element to it, it already places in the prepared container, not on the global page

![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/5fcd964c-83f8-4460-b675-6cfaa575fd29)

2023-08-31 16:41 UTC, Monyster commented
Ok, I changed :sticky to :fixed and change styles for page layout.

2023-08-31 16:41 UTC, Simpsonkk approved these changes

2023-09-01 06:27 UTC, nikita-remeslov approved these changes

2023-09-01 06:27 UTC, merged