bt-196: Add authorization check in protecter route component
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #200
Opened 2023-08-31 20:42 UTC by MChornomaz

2023-09-01 06:31 UTC, nikita-remeslov requested changes

2023-09-01 06:31 UTC, nikita-remeslov commented on frontend/src/bundles/auth/components/protected-route/protected-route.tsx
> +    const hasUser = Boolean(currentUser.id);
```suggestion
    const hasUser = Boolean(currentUser);
```

2023-09-02 11:59 UTC, nikita-remeslov approved these changes

2023-09-03 12:40 UTC, Monyster approved these changes

2023-09-04 06:26 UTC, merged