bt-168: Create Talent Sign up fourth step form
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #202
Opened 2023-09-01 06:29 UTC by nika-sirak

I created sign up talent fourth step form. Added validation. Also added properties for Button and Typography component, and expanded the functionality of the hook - useAppForm. 
I had a lot of issues with file input, and the solution I implemented was the only way that worked without errors.

<img width="685" alt="Screenshot 2023-09-01 at 07 20 13" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/60103912/17620f7e-655f-4563-8caa-1e55ccb93625">

<img width="685" alt="Screenshot 2023-09-01 at 07 17 01" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/60103912/2ec051c4-f71c-4430-ac2e-9bf270486c17">

2023-09-01 08:51 UTC, nikita-remeslov requested changes
Discussed changes in Slack

2023-09-04 06:40 UTC, nikita-remeslov requested changes

2023-09-04 06:40 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/input-file/input-file.tsx
I think it should be just a common component, all logic related to set error should be in the parent component

2023-09-04 06:40 UTC, nikita-remeslov commented on frontend/src/bundles/sign-up/components/fourth-step/fourth-step.tsx
> +                        setUrl={setPhotoURL}
onChange

2023-09-05 06:39 UTC, nikita-remeslov requested changes
In general looks good

2023-09-05 06:39 UTC, nikita-remeslov commented on frontend/src/assets/css/scaffolding.scss
> -
why do we need these changes?

2023-09-05 06:39 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/components.ts
>  export { Button } from './button/button.js';
if you need type, add it here

2023-09-05 06:39 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/file-upload/file-upload.tsx
> +import { type ButtonProperties } from '../button/button.js';
import form component.ts

2023-09-05 06:39 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/file-upload/file-upload.tsx
> +            <Controller name={name} control={control} render={renderInput} />
why you don't want to keep the Controller in the parent component?

2023-09-05 06:39 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/enums/steps.enum.ts
> +    STEP_04: 'Contacts and CV',
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/78347072/e9bd6356-f790-4d48-99ff-b06acde38cf1)

2023-09-05 07:41 UTC, nika-sirak commented on frontend/src/assets/css/scaffolding.scss
> -
These styles are useless

2023-09-05 13:59 UTC, savinaDaria approved these changes
Data from fields is validated and saved in Store.
As for files, we discussed that they will be pushed to backend and then returned data(url) will be saved in Store later 
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/58756139/c341225e-0f1c-4a7c-94d8-bb0ee4cfe117)

2023-09-06 09:51 UTC, illia-dobro commented on shared/src/bundles/talent-onboarding/enums/contacts-cv-step.validation-message.ts
> +    PHONE_NUMDER_REQUIRED: 'Phone number is required',
Some spelling mistakes:  PHONE_NUMDER_REQUIRED,  LINKRDIN_LINK_LENGTH:

2023-09-06 11:13 UTC, nika-sirak commented on shared/src/bundles/talent-onboarding/enums/contacts-cv-step.validation-message.ts
> +    PHONE_NUMDER_REQUIRED: 'Phone number is required',
thx

2023-09-06 11:45 UTC, MaksymGavatuk requested changes

2023-09-06 11:45 UTC, MaksymGavatuk commented on frontend/src/bundles/talent-onboarding/components/contacts-cv-step/contacts-cv-step.tsx
> +                const [file] = [...event.target.files];
I think we can do just:
```suggestion
                const [file] = event.target.files;
```

2023-09-06 11:45 UTC, MaksymGavatuk commented on frontend/src/bundles/talent-onboarding/components/contacts-cv-step/contacts-cv-step.tsx
> +                const [file] = [...event.target.files];
The same
```suggestion
                const [file] = event.target.files;
```

2023-09-06 11:45 UTC, MaksymGavatuk commented on frontend/src/bundles/talent-onboarding/helpers/validate-file-size.ts
> +        throw new Error('asdf');
What asdf mean ?

2023-09-06 15:17 UTC, nikita-remeslov requested changes
In general looks good

2023-09-06 15:17 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/components/contacts-cv-step/contacts-cv-step.tsx
> +    //delete this after the comments have been uncommented.
```suggestion
    //TODO: delete this after the comments have been uncommented.
```

2023-09-06 15:17 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/components/contacts-cv-step/contacts-cv-step.tsx
> +    //delete this after the comments have been uncommented.
Not a blocker. When you add TODO it will be much easier to find it

2023-09-06 15:17 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/components/contacts-cv-step/styles.module.scss
> +// @media screen and (max-width: 1210px) {
Do we need this code?

2023-09-06 15:17 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/components/step-navigation/step-navigation.tsx
> +    // const CV: React.FC = () => <button>CV and contacts</button>;
looks like it is mock. we can remove it

2023-09-06 17:11 UTC, nikita-remeslov approved these changes

2023-09-06 17:11 UTC, merged