bt-157: add file extension
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #205
Opened 2023-09-01 07:21 UTC by mskmee

2023-09-01 08:51 UTC, nikita-remeslov requested changes

2023-09-01 08:51 UTC, nikita-remeslov commented on shared/src/bundles/users/validation-schemas/user-sign-in.validation-schema.ts
create a folder for this file 'constants' - shared/src/bundles/users/validation-schemas/auth-constants.ts

also, rename it to `constants.ts`

2023-09-02 17:03 UTC, anton-otroshchenko approved these changes

2023-09-02 19:27 UTC, nikita-remeslov requested changes
Conflicts

2023-09-02 19:27 UTC, nikita-remeslov commented on shared/src/bundles/users/validation-schemas/constants/constants.ts
`AUTH_CONSTANTS` better name

2023-09-03 06:22 UTC, mskmee commented on shared/src/bundles/users/validation-schemas/constants/constants.ts
fix

2023-09-04 06:30 UTC, nikita-remeslov requested changes
if you want to keep your file name.

1. Rename auth.contants.ts
2. Create root file constants.ts

2023-09-05 12:31 UTC, nikita-remeslov approved these changes

2023-09-05 12:42 UTC, merged