bt-222: Click on logo redirects to main page
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #226
Opened 2023-09-04 11:36 UTC by vladjsp

2023-09-04 21:04 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/logo/logo.tsx
what happens if I want to use just the logo? Without link?

2023-09-05 11:52 UTC, vladjsp commented
Added a link props to the Logo and fixed Sidebar styles for logo and structure.

2023-09-05 21:11 UTC, Monyster requested changes

2023-09-05 21:11 UTC, Monyster commented on frontend/src/bundles/common/components/logo/logo.tsx
> +                <Grid className={getValidClassNames(styles.logo, className)}>
```suggestion
                <Grid container item className={getValidClassNames(styles.logo, className)}>
```
styles.logo will not be applied if grid is not container

2023-09-06 14:51 UTC, vladjsp commented on frontend/src/bundles/common/components/logo/logo.tsx
> +                <Grid className={getValidClassNames(styles.logo, className)}>
True. I will fix this.

2023-09-11 14:23 UTC, nikita-remeslov requested changes

2023-09-11 14:23 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/logo/logo.tsx
> +            {link === AppRoute.ROOT ? (
this check does not work. it works only for the root page. I think it is better to pass some flag `withLink`.

2023-09-11 20:23 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/logo/logo.tsx
> +    link = AppRoute.ROOT,
we can remove this props

2023-09-11 20:23 UTC, nikita-remeslov approved these changes

2023-09-12 10:17 UTC, anton-otroshchenko approved these changes

2023-09-12 10:20 UTC, merged