bt-236: Passed rest properties
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #242
Opened 2023-09-05 02:18 UTC by JosuerBague

Passed rest properties to components

2023-09-05 06:25 UTC, nikita-remeslov requested changes
check ticket description

2023-09-05 21:36 UTC, Monyster approved these changes

2023-09-06 07:46 UTC, MaksymGavatuk approved these changes

2023-09-06 15:20 UTC, nikita-remeslov approved these changes

2023-09-06 15:20 UTC, merged