bt-232: Connect signIn to api
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #247
Opened 2023-09-05 08:51 UTC by vladjsp

2023-09-05 09:32 UTC, vladjsp commented
![signIn](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/0f528a62-01e6-404a-a26b-3a0b04add690)

2023-09-05 09:37 UTC, vladjsp commented
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/4106aed1-3dd5-4ac0-a0c8-29d176ae36b3

2023-09-05 11:43 UTC, JosuerBague approved these changes
Tested locally on my machine.

Everything looks correct and working.

2023-09-05 13:40 UTC, mskmee commented on frontend/src/bundles/auth/store/slice.ts
> +            )
Guess we should set current user to null in this matchers

2023-09-06 06:39 UTC, nikita-remeslov requested changes

2023-09-06 06:39 UTC, nikita-remeslov commented on frontend/src/bundles/auth/store/slice.ts
> +                    state.currentUser = action.payload;
```suggestion
                    state.currentUser = null;
```

2023-09-06 07:32 UTC, nikita-remeslov commented on frontend/src/bundles/auth/store/slice.ts
> +                    state.dataStatus = DataStatus.REJECTED;
```suggestion
                    state.dataStatus = DataStatus.REJECTED;
                    state.currentUser = null;
```

2023-09-06 15:23 UTC, nikita-remeslov approved these changes

2023-09-06 15:23 UTC, merged