bt-268: Authorization plugin. Improving error return.
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #269
Opened 2023-09-05 20:20 UTC by Monyster

Closes #268

2023-09-06 05:57 UTC, JosuerBague approved these changes

2023-09-06 07:42 UTC, MaksymGavatuk approved these changes

2023-09-08 06:53 UTC, nikita-remeslov requested changes

2023-09-08 06:53 UTC, nikita-remeslov commented on backend/src/common/plugins/authorization/authorization.plugin.ts
> +                message: ErrorMessages.MISSING_TOKEN,
Unauthorized user

2023-09-08 06:53 UTC, nikita-remeslov commented on shared/src/enums/error-messages.enum.ts
we must keep errors universal so that later we can validate them more easily if necessary

2023-09-08 08:15 UTC, Monyster commented on backend/src/common/plugins/authorization/authorization.plugin.ts
> +                message: ErrorMessages.MISSING_TOKEN,
You mean something like this?
```js
 if (!token) {
    throw new HttpError({
        message: ErrorMessages.UNAUTHORIZED_USER,     <--- "User not authorized"
        status: HttpCode.UNAUTHORIZED,       <--- 401
    });
}
```

2023-09-11 06:57 UTC, nikita-remeslov requested changes

2023-09-11 06:57 UTC, nikita-remeslov commented on shared/src/enums/error-messages.enum.ts
> +    MISSING_TOKEN: 'Missing token.',
```suggestion
```

2023-09-11 13:50 UTC, nikita-remeslov approved these changes

2023-09-11 13:50 UTC, merged