bt-250: Create file upload endpoint
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #273
Opened 2023-09-06 11:00 UTC by JosuerBague

Closes #250 

Whats been done:

- file-storage using AWS S3
- file controller
- file service
- file repository

Tested using thunder client:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/b47d1f7e-d178-465f-bb87-125c0f8aca04)

Entity stored in database:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/2c7838c6-7810-4fbc-83af-8551051bf89d)

2023-09-06 15:25 UTC, MaksymGavatuk requested changes

2023-09-06 15:25 UTC, MaksymGavatuk commented on backend/src/migrations/20230906094421_update_files_table.ts
> +    UPDATED_AT: 'updated_at',
If you don't use CONTENT_TYPE, CREATED_AT, etc remove these fields

2023-09-06 15:25 UTC, MaksymGavatuk commented on backend/src/migrations/20230906094421_update_files_table.ts
> +};
In this case create OldColumnName = { ... } NewColumnName = { ... }

2023-09-06 15:25 UTC, MaksymGavatuk commented on backend/.env.example
> +AWS_SECRET_ACCESS_KEY=string
Forgot AWS_BUCKET_NAME

2023-09-06 15:25 UTC, MaksymGavatuk commented on backend/src/common/packages/file-storage/file-storage.package.ts
> +    }
Pass this variables like constructor params

2023-09-07 10:05 UTC, JosuerBague commented
Retested image and file upload using curl:

Pdf
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/d6c4d9e4-8afa-4cf1-8b9b-cf001fa6d3b9)

Png:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/e7761ac1-5d0f-4686-8ed2-ed9cb98c8c82)

Files are in bucket:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/5d009fd4-b2e3-45eb-93dd-790f6f2fd308)

Entity details are stored in db:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/80ab3b95-4e51-4281-ab9f-d7812f2ead5b)

2023-09-07 10:14 UTC, MaksymGavatuk approved these changes
Looks good for me

2023-09-11 08:37 UTC, ptarho approved these changes

2023-09-11 14:25 UTC, nikita-remeslov commented
Conflicts

2023-09-11 14:26 UTC, nikita-remeslov requested changes

2023-09-11 14:26 UTC, nikita-remeslov commented on backend/.env.example
EOL

2023-09-11 14:26 UTC, nikita-remeslov commented on backend/src/bundles/files/file.entity.ts
why do we need this changes?

2023-09-12 00:52 UTC, JosuerBague commented on backend/src/bundles/files/file.entity.ts
Hello, I discussed this in Slack with @MaksymGavatuk and in the end it was decided that for files only the following columns were needed:
- id
- url
- created_at
- updated_at
- etag
- file_name

2023-09-12 10:17 UTC, nikita-remeslov approved these changes

2023-09-12 10:17 UTC, merged