bt-276: [ BUG FIX ] sign up page layout needs improvement
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #277
Opened 2023-09-06 15:01 UTC by JosuerBague

Closes #276

This contains changes that affect the Input component (Cause of the error message bug described in ticket).

Removed dummy text.
Add Logo.
Separated auth routing from being app child route. 

Desktop:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/799ea82a-a07f-4ead-990e-c3430225b688)

Mobile:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/d1ee2057-aaea-4aab-8351-998b6850548b)

2023-09-06 15:51 UTC, vladjsp approved these changes
Looks good. Tested it locally with and without new Terms checkbox.

2023-09-07 07:59 UTC, Monyster requested changes
Resizing inputs when an error occurs
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/442234bc-6206-4c56-99f3-509fe966559f)

2023-09-07 08:09 UTC, Monyster requested changes

2023-09-07 08:09 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx
> +                        'input-container',
```suggestion
                        'inputContainer',
```

2023-09-07 08:09 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx
> +                        'input-container',
```suggestion
                        'inputContainer',
```

2023-09-07 09:13 UTC, JosuerBague commented
> Resizing inputs when an error occurs ![image](https://user-images.githubusercontent.com/42421305/266247162-442234bc-6206-4c56-99f3-509fe966559f.png)
> 
> If you made changes I ask for below, inputs will be corrected

Yep, made these changes before classNames ticket got merged. Should be okay now.

2023-09-07 10:07 UTC, Monyster approved these changes

2023-09-07 10:44 UTC, nikita-remeslov approved these changes

2023-09-07 10:44 UTC, merged