Task/bt 257 create onboarding step2
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #283
Opened 2023-09-06 19:56 UTC by savinaDaria

#257 
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/58756139/1ae6b914-e722-469e-a7ef-8e0a705311a2)

2023-09-06 22:15 UTC, nika-sirak commented on frontend/src/bundles/talent-onboarding/components/bsa-badges-step/bsa-badges-step.tsx
> +import { FormHelperText } from '@mui/material';
change import { FormHelperText} from '~/bundles/common/components/components.js';

2023-09-06 22:19 UTC, nika-sirak commented on frontend/src/bundles/talent-onboarding/components/bsa-badges-step/bsa-badges-step.tsx
> +import { useSelector } from 'react-redux';
import { useAppSelector} from '~/bundles/common/hooks/hooks.js';

2023-09-07 06:46 UTC, nikita-remeslov requested changes

2023-09-07 06:46 UTC, nikita-remeslov commented on frontend/src/bundles/lms/mock-data/mock-badges.constants.ts
we will use this data only in the onboarding. I think we can keep it in the `talent-onboarding` bundle

2023-09-07 06:46 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/context/form-submit-provider.context.tsx
> +// Custom hook to use the context
why do we need this hook?

2023-09-07 07:41 UTC, savinaDaria commented on frontend/src/bundles/talent-onboarding/context/form-submit-provider.context.tsx
> +// Custom hook to use the context
@nikita-remeslov I used it here to test step data saving onSubmit, but actually it is added in _combine talent onboarding PR_
I'll comment/delete stuff related to it

2023-09-07 08:19 UTC, anton-otroshchenko requested changes

2023-09-07 08:19 UTC, anton-otroshchenko commented on frontend/src/bundles/talent-onboarding/components/bsa-badges-step/bsa-badges-step.tsx
> +    );
I think you don't need two useSelector's here.

Maybe this approach will be better

```
const { savedPayload, bsaBadges } =
    useAppSelector((state) => ({
      savedPayload: state.talentOnBoarding.bsaBadgesStep,
      bsaBadges: state.lms.bsaBadges,
    }));
```

2023-09-07 08:29 UTC, nika-sirak approved these changes

2023-09-07 08:53 UTC, nikita-remeslov approved these changes

2023-09-07 08:57 UTC, anton-otroshchenko approved these changes

2023-09-07 08:57 UTC, merged