bt-24: AWS deployment
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #303
Opened 2023-09-07 12:55 UTC by MaksymGavatuk

2023-09-07 12:59 UTC, katerynakostikova commented on .github/workflows/cd.yml
> +  ENVIRONMENT: ${{ github.ref_name }}
```suggestion
env:
    AWS_REGION: us-east-1
    EBS_APP_NAME: bsa-talents
    ENVIRONMENT: ${{ github.ref_name }}
```
and so on

2023-09-07 13:19 UTC, MaksymGavatuk commented on .github/workflows/cd.yml
> +  ENVIRONMENT: ${{ github.ref_name }}
Oh yes 😅 Thanks

2023-09-08 06:17 UTC, nikita-remeslov requested changes
we should update GitHub Actions, they require npm 9

2023-09-08 06:17 UTC, nikita-remeslov commented on prepare-build.sh
eol

2023-09-08 08:34 UTC, nikita-remeslov approved these changes

2023-09-08 08:36 UTC, nikita-remeslov approved these changes

2023-09-08 08:46 UTC, merged