bt-301: Fix title for ExperienceYears on slider
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #304
Opened 2023-09-07 13:10 UTC by anogire

<img width="392" alt="Screenshot 2023-09-07 at 15 14 39" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/a1f4cc87-2f82-4df7-8cc3-c7baec6568f8">
<img width="392" alt="Screenshot 2023-09-07 at 15 14 34" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/f0229ccf-7d78-46ab-b5a3-bc5407692378">
<img width="392" alt="Screenshot 2023-09-07 at 15 14 25" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/004bc8d7-69fa-46ca-882c-e99d67248060">

2023-09-08 06:48 UTC, nikita-remeslov requested changes

2023-09-08 06:48 UTC, nikita-remeslov commented on mobile/src/bundles/common/helpers/get-years-title/get-years-title.ts
> +    return value ? `${value} year${value === singleYear ? '' : 's'}` : 'no';
Conditional operator in Conditional operator. Try to write few unit test for it)

2023-09-08 06:48 UTC, nikita-remeslov commented on mobile/src/bundles/common/helpers/get-years-title/get-years-title.ts
> +    return value ? `${value} year${value === singleYear ? '' : 's'}` : 'no';
we can simplify it

2023-09-08 14:15 UTC, katerynakostikova commented
I'd better pass value to selector like this, value and label array of objects 
The label can be undefined and if yes, we just show value, if there is a label we'll show it 
In that way label can be whatever you want

2023-09-08 17:43 UTC, anogire commented
<img width="369" alt="Screenshot 2023-09-08 at 20 23 56" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/3c59d7d6-d385-4d18-b4d9-903601964304">
<img width="369" alt="Screenshot 2023-09-08 at 20 24 02" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/cd2d8f88-b607-4d56-8caf-1c706198bc19">
<img width="369" alt="Screenshot 2023-09-08 at 20 24 10" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/37ed5a68-5d0a-4f89-a041-543b2e4df019">
<img width="369" alt="Screenshot 2023-09-08 at 20 24 16" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/e57682a5-cb7c-46b5-99be-a2dbab71eff7">
<img width="369" alt="Screenshot 2023-09-08 at 20 24 21" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/fd1c674e-e45a-4701-b404-b8c0b1692697">
<img width="369" alt="Screenshot 2023-09-08 at 20 24 25" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/e11b1baf-4d10-4fdd-bcfe-6435c382b7de">

But, if there is no label (in some other case) It will look like this. I could not move it more closely. :(
<img width="369" alt="Screenshot 2023-09-08 at 20 27 03" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/41402ba3-16ff-444f-81df-8022d4b5f3ff">
<img width="369" alt="Screenshot 2023-09-08 at 20 27 10" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/16bc6557-0df2-4e50-8edd-cf78e5a44df9">

2023-09-11 10:05 UTC, katerynakostikova approved these changes

2023-09-11 11:11 UTC, nikita-remeslov approved these changes

2023-09-11 11:11 UTC, merged