bt-323: [BUG FIX] no redirect to 404 on wrong url
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #342
Opened 2023-09-09 06:41 UTC by JosuerBague

This fixes the previous behaviour where accessing invalid routes of `/talent/onboarding/steps/:step` would not render the not found page.

Issue was caused by :step params defaulting to 'profile' when :step was not a valid onboarding route.

These changes include a refactoring of the constants found in:
`frontend/src/bundles/talent-onboarding/constants/constants.ts`

Further Route issues (structure and protected routes) are being addressed in the following PR: https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/309

2023-09-11 07:09 UTC, nikita-remeslov requested changes

2023-09-11 07:09 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/constants/constants.ts
why do we need this constant?

2023-09-11 07:09 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/constants/constants.ts
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/blob/development/frontend/src/index.tsx#L35-L79

also, these routes should be children of App.tsx.

2023-09-12 04:31 UTC, JosuerBague commented on frontend/src/bundles/talent-onboarding/constants/constants.ts
It's being used in finding what slug was used for navigating to this particular onboarding path. I did not implement it, just refactored a bit while experimenting with it when I was fixing the 404 not found.

Should I remove these changes?

2023-09-12 11:57 UTC, JosuerBague commented
Redundant PR, bug was fixed in another ticket.

2023-09-12 11:57 UTC, closed without merging