Task/bt 17 add app theme
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #36
Opened 2023-08-21 12:51 UTC by illia-dobro

2023-08-21 12:56 UTC, katerynakostikova commented on mobile/src/bundles/common/styles/colors.ts
> +};
```suggestion
const Color = {
    PRIMARY: '#274F8D',
    SECONDARY: '#18A0FB',
    ...
} as const;
```

2023-08-21 13:13 UTC, nikita-remeslov requested changes
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/actions/runs/5926475879/job/16067962200?pr=36

2023-08-21 13:22 UTC, katerynakostikova commented on mobile/src/bundles/common/styles/colors.ts
> +};
updated comment

2023-08-21 13:43 UTC, katerynakostikova approved these changes

2023-08-21 14:17 UTC, anogire approved these changes

2023-08-21 14:28 UTC, katerynakostikova approved these changes

2023-08-21 14:28 UTC, katerynakostikova commented on mobile/src/bundles/common/styles/colors.ts
> +}
We discussed switching from ts enums to js enums with coaches, so let's replace with js enum 
```suggestion
const Color = {
    PRIMARY: '#274F8D',
    SECONDARY: '#18A0FB',
    ...
} as const;
```

2023-08-22 06:23 UTC, nikita-remeslov approved these changes

2023-08-22 06:25 UTC, nikita-remeslov requested changes

2023-08-22 06:25 UTC, nikita-remeslov commented on mobile/src/bundles/common/styles/colors.ts
I think we should rename this file as we use enum for it 

`colors.enum.ts`

2023-08-22 09:11 UTC, katerynakostikova reviewed
Please move this file to bundles/common/enums/ui

2023-08-22 09:28 UTC, katerynakostikova commented
<img width="523" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/2fed4058-ab6d-4dd4-962e-284ee0e5d9d3">
Re-export it here

2023-08-22 09:41 UTC, katerynakostikova approved these changes

2023-08-22 09:45 UTC, nikita-remeslov approved these changes
@illia-dobro fix conflicts please
@katerynakostikova after you can merge

2023-08-22 10:00 UTC, merged