bt-274: [BUG] Step 4 doesn't correspond the design
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #377
Opened 2023-09-11 17:35 UTC by nika-sirak

2023-09-11 20:44 UTC, nikita-remeslov requested changes

2023-09-11 20:44 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/components/contacts-cv-step/styles.module.scss
> +    & span {
B10 - https://github.com/BinaryStudioAcademy/quality-criteria/blob/production/src/javascript.md

2023-09-11 20:44 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/enums/steps.enum.ts
>      STEP_01: 'Profile',
```js
    Step.STEP_1: 'Profile',
```
you can reuse enum here 
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/blob/b84788183c2c9e4e428a8a75469d2dfbb03695ed/shared/src/bundles/user-details/enums/completed-step.enum.ts

2023-09-13 06:46 UTC, nikita-remeslov approved these changes

2023-09-13 11:18 UTC, lavandosya approved these changes

2023-09-14 06:36 UTC, nikita-remeslov commented
Conflicts

2023-09-14 07:07 UTC, merged