bt-357: [BUG] The "I'm hiring/ I'm looking for the job" radio buttons go outside of the Sign up form
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #383
Opened 2023-09-12 06:54 UTC by illia-dobro

![1](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/48f93831-1e59-4c17-b1ad-7df71bec0e8b)

if size bigger:
![2](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/7820f663-7367-4f90-8ca7-846f5a848689)

2023-09-12 10:15 UTC, nikita-remeslov requested changes

2023-09-12 10:15 UTC, nikita-remeslov commented on package-lock.json
I think we dont need these changes.

2023-09-12 14:30 UTC, katerynakostikova requested changes

2023-09-12 14:30 UTC, katerynakostikova commented on mobile/src/bundles/common/components/radio-buttons/radio-buttons.tsx
> +                containerStyle={{ flexWrap: 'wrap' }}
avoid inline styles, it should be moved to styles file

2023-09-12 15:33 UTC, katerynakostikova approved these changes

2023-09-13 11:10 UTC, anogire approved these changes

2023-09-13 12:30 UTC, likeri29 approved these changes

2023-09-13 13:17 UTC, merged