bt-461: Create characteristics component in admin user verification
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #491
Opened 2023-09-17 16:32 UTC by Monyster

Closes #461 

![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/d4473311-4043-479b-8e5c-874f70ca9412)

2023-09-17 20:07 UTC, nika-sirak commented on frontend/src/bundles/common/components/multi-read/styles.module.scss
> +}
--slate-gray: #7c8798;

2023-09-17 20:07 UTC, nika-sirak commented on frontend/src/bundles/common/components/multi-read/styles.module.scss
> +    border: 1px solid #f6f7f9;
maybe better add to css variables

2023-09-17 20:07 UTC, nika-sirak commented on frontend/src/bundles/admin/components/characteristics/characteristics.tsx
> +                        padding: '20px',
Can you put those styles in scss file?

2023-09-20 09:38 UTC, nikita-remeslov requested changes

2023-09-20 09:38 UTC, nikita-remeslov commented on frontend/src/bundles/admin/components/characteristics/characteristics.tsx
> +// Mock data
add todo comment, to remove it

2023-09-20 15:28 UTC, Monyster commented on frontend/src/bundles/admin/components/characteristics/characteristics.tsx
> +// Mock data
changed to mock-data/mock-personality-type-options.ts

2023-09-21 09:14 UTC, nikita-remeslov approved these changes

2023-09-22 06:48 UTC, nikita-remeslov approved these changes

2023-09-22 06:49 UTC, merged