bt-397: Add transition to elements for Onboarding Flow
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #492
Opened 2023-09-17 18:16 UTC by Monyster

Closes #397

2023-09-20 07:13 UTC, MaksymGavatuk requested changes

2023-09-20 07:13 UTC, MaksymGavatuk commented on frontend/src/bundles/common/components/select/styles.module.scss
> +// }
Remove comments if we don't need this

2023-09-20 09:41 UTC, nikita-remeslov requested changes
in the design blue line in one place. we just need to add a transition on elements state (hover, error, etc.)

2023-09-20 13:40 UTC, Monyster commented
@nikita-remeslov I can remove it, but as I see on other sites, it should be a moving underline or progress bar.
I can change it to the progress bar style.

If you look at the design, you'll see that this is not a decorative underline for the step name.
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/4d59e8ce-0b16-4f9c-8568-d5840a1db78b)

I suggest to do as shown next
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/5eb86cbd-3e99-4f4a-bb23-7bb4f166a1f5)
OR
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/40326ed6-137f-4dc8-a478-9077174bd40a)

2023-09-21 09:28 UTC, nikita-remeslov requested changes

2023-09-21 09:28 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/constants/constants.ts
> +const STEP_FIVE = 5;
should be enum

2023-09-22 06:50 UTC, nikita-remeslov requested changes

2023-09-22 06:50 UTC, nikita-remeslov commented on frontend/src/bundles/talent-onboarding/constants/constants.ts
> +};
check how we create enums

2023-09-22 17:49 UTC, Monyster commented on frontend/src/bundles/talent-onboarding/constants/constants.ts
> +};
as const

2023-09-25 08:35 UTC, nikita-remeslov commented
conflicts

2023-09-25 19:09 UTC, nikita-remeslov approved these changes

2023-09-25 19:09 UTC, merged