bt-486: [BUG] Badge's layout isn't displayed according to design on the Scores & Skills tab
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #501
Opened 2023-09-18 09:40 UTC by illia-dobro

Different phone settings: font size
![normal](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/82f3e4f1-55b4-4820-aa3f-184c83b23bd3)
![av](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/ee8c1a3f-1990-44b9-b5e6-2f9e00585516)
 
Max phone settings: font size and display size: (word “communication” breaks here)
![maxfont](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/2c05805e-913f-4d21-a4de-1b0f9b1ac952)

2023-09-18 12:59 UTC, katerynakostikova requested changes

2023-09-18 12:59 UTC, katerynakostikova commented on mobile/src/bundles/common/components/badge/styles.ts
> +        width: '48.6%',
this is not good way to fix this issue

2023-09-18 12:59 UTC, katerynakostikova commented on mobile/src/bundles/common/components/badge/badge.tsx
> +                                : TextCategory.H4
repeating of code, move to some const

2023-09-19 05:52 UTC, mskmee approved these changes

2023-09-19 07:41 UTC, katerynakostikova approved these changes

2023-09-19 09:43 UTC, merged