bt-345: Get badges and hard skills from api
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #549
Opened 2023-09-19 18:02 UTC by vladjsp

closes https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/345

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/7d99eb58-d9ad-42ca-9028-ebfd264db35d

2023-09-20 12:38 UTC, MaksymGavatuk requested changes

2023-09-20 12:38 UTC, MaksymGavatuk commented on frontend/src/bundles/common-data/types/bsa-badges-response-dto.type.ts
> +    }[];
Create type for this items

2023-09-20 12:38 UTC, MaksymGavatuk commented on frontend/src/bundles/common-data/types/hard-skills-response-dto.type.ts
> +    }[];
The same

2023-09-20 12:38 UTC, MaksymGavatuk commented on frontend/src/bundles/common-data/store/actions.ts
> +    return await commonDataApi.getAllBsaBadges();
Don't use return await

2023-09-20 12:38 UTC, MaksymGavatuk commented on frontend/src/bundles/common-data/store/actions.ts
> +    return await commonDataApi.getAllHardSkills();
The same

2023-09-20 12:38 UTC, MaksymGavatuk commented on frontend/src/bundles/common-data/common-data-api.ts
> +        return await response.json<HardSkillsResponseDto>();
The same

2023-09-20 12:38 UTC, MaksymGavatuk commented on frontend/src/bundles/common-data/common-data-api.ts
> +        return await response.json<BsaBadgesResponseDto>();
The same

2023-09-20 22:16 UTC, savinaDaria approved these changes
Tested, badges and hard-skills are returned.

2023-09-21 08:50 UTC, nikita-remeslov requested changes
Discussed in Slack

2023-09-25 08:06 UTC, nikita-remeslov approved these changes

2023-09-25 08:06 UTC, merged