bt-22: Add FormControl and FormLabel components
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #56
Opened 2023-08-21 20:28 UTC by Monyster

Closes #22 

Examples of usage:
```js
<FormControl variant="standard">
    <InputLabel htmlFor="component-simple">Name</InputLabel>
    <Input
        id="component-simple"
        defaultValue="Composed TextField"
    />
</FormControl>
```
```js
<FormControl variant="standard">
<InputLabel htmlFor="component-helper">Name</InputLabel>
<Input
  id="component-helper"
  defaultValue="Composed TextField"
  aria-describedby="component-helper-text"
/>
<FormHelperText id="component-helper-text">
  Some important helper text
</FormHelperText>
</FormControl>
```
```js
<FormControl isDisabled variant="standard">
<InputLabel htmlFor="component-disabled">Name</InputLabel>
<Input
  id="component-disabled"
  defaultValue="Composed TextField"
/>
<FormHelperText>Disabled</FormHelperText>
</FormControl>
```
```js
<FormControl isError variant="standard">
<InputLabel htmlFor="component-error">Name</InputLabel>
<Input
  id="component-error"
  defaultValue="Composed TextField"
  aria-describedby="component-error-text"
/>
<FormHelperText id="component-error-text">
  Error
</FormHelperText>
</FormControl>
```
```js
<FormControl variant="outlined">
<InputLabel htmlFor="component-outlined">Name</InputLabel>
<OutlinedInput
  id="component-outlined"
  defaultValue="Composed TextField"
  label="Name"
/>
```
```js
</FormControl>
<FormControl variant="filled">
<InputLabel htmlFor="component-filled">Name</InputLabel>
<FilledInput
  id="component-filled"
  defaultValue="Composed TextField"
/>
</FormControl>
```
```js
<FormControl
sx={{
width: '300px',
display: 'flex',
gap: '10px',
padding: '20px',
}}
>
<FormLabel>Form Label</FormLabel>

<FormControl variant="outlined">
<InputLabel htmlFor="component-outlined">Name</InputLabel>
<OutlinedInput id="component-outlined" label="Name" />
</FormControl>

<FormControl variant="filled">
<InputLabel htmlFor="component-filled">Email</InputLabel>
<FilledInput id="component-filled" />
</FormControl>
</FormControl>
```

Example image:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/42421305/e57ff821-61ab-4648-b851-d6d269f3b918)

2023-08-22 10:08 UTC, MaksymGavatuk requested changes

2023-08-22 10:08 UTC, MaksymGavatuk commented on frontend/src/bundles/common/components/form-control/form-control.tsx
> +    variant = 'standard',
In this case you should use your object values:

```suggestion

    variant = InputVariantTypes.STANDART,
```

2023-08-22 10:08 UTC, MaksymGavatuk commented on frontend/src/bundles/common/components/form-control/form-control.tsx
> +    (typeof InputVariantTypes)[keyof typeof InputVariantTypes];
In this case you need to use ValueOf types to set type for ex: ValueOf<typeof InputVariantTypes>

2023-08-22 10:08 UTC, MaksymGavatuk commented on frontend/src/bundles/common/components/form-control/form-control.tsx
> +} as const;
Move it to enums folder

2023-08-23 06:47 UTC, nikita-remeslov requested changes
export components in the root components.ts file

2023-08-23 19:41 UTC, nikita-remeslov approved these changes

2023-08-23 19:41 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/form-control/form-control.tsx
> +    isError = false,
```suggestion
    hasError = false,
```

2023-08-23 19:42 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/form-label/form-label.tsx
> +    ...properties
```suggestion
    ...props
```

2023-08-23 19:42 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/form-label/form-label.tsx
> +    <MUIFormLabel className={className} {...properties}>
```suggestion
    <MUIFormLabel className={className} {...props}>
```

2023-08-24 06:55 UTC, JosuerBague reviewed
Looks good to me.

2023-08-24 06:55 UTC, MaksymGavatuk approved these changes

2023-08-24 06:56 UTC, nikita-remeslov commented
Fix conflicts and we can merge

2023-08-24 08:30 UTC, ptarho commented on frontend/src/bundles/common/components/components.ts
> +export { FormControl } from './form-control/form-control.js';
You forget to export FormLabel

2023-08-25 05:55 UTC, nikita-remeslov approved these changes

2023-08-25 05:56 UTC, merged