bt-565: Add ability to view password during signin signup
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #574
Opened 2023-09-20 16:58 UTC by vladjsp

closes https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/565

https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/5932ffbf-7464-4973-8254-6cff2de71a84

2023-09-20 19:40 UTC, Simpsonkk approved these changes
I can see and hide my password on sign in and sign up pages.

2023-09-20 22:24 UTC, savinaDaria approved these changes

2023-09-21 09:34 UTC, nikita-remeslov commented
Conflicts

2023-09-22 06:36 UTC, nikita-remeslov requested changes

2023-09-22 06:36 UTC, nikita-remeslov commented on frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx
> +        ></PasswordVisibility>
```suggestion
        />
```

2023-09-22 06:36 UTC, nikita-remeslov commented on frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx
> +        ></PasswordVisibility>
the same

2023-09-22 07:07 UTC, vladjsp commented on frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx
> +        ></PasswordVisibility>
fixed

2023-09-22 07:08 UTC, vladjsp commented on frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx
> +        ></PasswordVisibility>
fixed

2023-09-25 08:05 UTC, nikita-remeslov approved these changes

2023-09-25 08:05 UTC, merged