bt-534: Create publish user endpoint
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #576
Opened 2023-09-20 18:59 UTC by MChornomaz

closes #534

2023-09-21 06:25 UTC, mskmee commented on backend/src/bundles/user-details/types/user-details-properties.type.ts
> +    isPublished: boolean;
we need to have date in publish field, to show it on employer page: 
<img width="512" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/85788646/43dbc4ff-6f7b-4ee5-96c4-7ee1c0755ce1">

2023-09-21 11:53 UTC, MaksymGavatuk requested changes

2023-09-21 11:53 UTC, MaksymGavatuk commented on backend/src/migrations/20230920210422_add_is_published_to_user_details_table.ts
> +        table.boolean('is_published').defaultTo(false);
If you set default value, I think we should make in notNullable ?

2023-09-22 06:52 UTC, nikita-remeslov approved these changes

2023-09-22 07:01 UTC, MaksymGavatuk approved these changes

2023-09-22 14:17 UTC, anton-otroshchenko approved these changes

2023-09-22 14:17 UTC, merged