bt-502: Mobile - Add verification message after onboarding steps for both roles
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #579
Opened 2023-09-21 06:34 UTC by illia-dobro

For employer, I will only add a message and not block other screens. If it is acceptable to the talent, I will make it similar to employer.

![apr](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/ac8b4d65-c02f-4336-b558-0e11f5e40131)
![mess](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/d696384f-0848-4cce-85b1-2a5c1e3aac67)

2023-09-21 12:02 UTC, katerynakostikova commented
Let's make some screen header like in candidates screen and put that tag there, it should also be like warning (some yellow colors)

2023-09-22 12:12 UTC, katerynakostikova requested changes

2023-09-22 12:12 UTC, katerynakostikova commented on mobile/src/bundles/common/components/verification-message/styles.ts
> +        right: 10,
let's avoid absolute positioning, we can just align items center in header

2023-09-22 12:12 UTC, katerynakostikova commented on mobile/src/bundles/common/components/verification-message/styles.ts
> +        borderRadius: 999,
why 999?

2023-09-22 12:12 UTC, katerynakostikova commented on mobile/src/bundles/common/components/verification-message/styles.ts
> +        shadowRadius: 3.84,
it's ios settings we don't need it

2023-09-22 12:12 UTC, katerynakostikova commented on mobile/src/bundles/common/components/verification-message/verification-message.tsx
> +    );
let's add this check directly in component where we use it

2023-09-22 12:12 UTC, katerynakostikova commented on mobile/src/bundles/employer/screens/employer-profile/employer-profile.tsx
> +            <VerificationMessage isApproved={false} />
can we get this data from the store? We already store user data there

2023-09-22 12:12 UTC, katerynakostikova commented on mobile/src/bundles/talent/store/slice.ts
> +    isApproved: false, //todo when real data appear
we still don't have it?

2023-09-25 07:37 UTC, katerynakostikova approved these changes

2023-09-25 12:24 UTC, anogire approved these changes

2023-09-25 13:43 UTC, merged