bt-48: + Create Grid Component
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #59
Opened 2023-08-22 05:22 UTC by JoshDagat

![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/a42b2855-2379-4c17-9ea2-f41ba76f9e61)

2023-08-22 05:56 UTC, mskmee approved these changes

2023-08-22 08:13 UTC, nikita-remeslov requested changes

2023-08-22 08:13 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/grid/grid.tsx
> +    classes,
```suggestion
```

2023-08-22 08:13 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/grid/grid.tsx
> +    component = 'div',
```suggestion
    component = 'div',
    ...props
```

2023-08-22 08:13 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/grid/grid.tsx
> +    component = 'div',
we also should add className

2023-08-22 08:13 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/grid/grid.tsx
> +        zeroMinWidth={zeroMinWidth}
```suggestion
        component={component}
        {...props}
```

2023-08-22 12:27 UTC, nikita-remeslov requested changes

2023-08-22 12:27 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/grid/grid.tsx
> +    ...properties
```suggestion
    ...props
```

2023-08-22 12:27 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/grid/grid.tsx
> +    <MUIGrid className={className} component={component} {...properties}>
```suggestion
    <MUIGrid className={className} component={component} {...props}>
```

2023-08-22 19:20 UTC, JosuerBague commented on frontend/src/bundles/common/components/grid/grid.tsx
> +    ...properties
Hello, I tried props first but linter wouldn't allow it, hence properties.

2023-08-23 06:35 UTC, nikita-remeslov commented on frontend/src/bundles/common/components/grid/grid.tsx
> +    ...properties
merge development branch

2023-08-23 06:36 UTC, nikita-remeslov commented
@JoshDagat Also you should import you component to the root component.ts file

2023-08-23 06:41 UTC, JoshDagat commented
D

> @JoshDagat Also you should import you component to the root component.ts file

Done.

2023-08-23 07:24 UTC, JosuerBague commented on frontend/src/bundles/common/components/grid/grid.tsx
> +    ...properties
Development branch merged and changes made (properties -> props).

2023-08-23 07:31 UTC, nikita-remeslov approved these changes

2023-08-23 07:31 UTC, merged