bt-537:  Fix spaces between required asterisk
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #590
Opened 2023-09-21 12:02 UTC by lavandosya

2023-09-22 06:53 UTC, nikita-remeslov approved these changes

2023-09-22 14:03 UTC, ptarho approved these changes

2023-09-24 09:01 UTC, Monyster requested changes

2023-09-24 09:01 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx
> +                    <FormLabel className="label">
```suggestion
                    <FormLabel className="label" required>
```

2023-09-24 09:01 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx
> +                        <span className={styles.required}>*</span>
```suggestion
                        
```

2023-09-24 09:01 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx
> +                    <FormLabel className="label">
```suggestion
                    <FormLabel className="label" required>
```

2023-09-24 09:01 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-in-form/sign-in-form.tsx
> +                        <span className={styles.required}>*</span>
```suggestion
```

2023-09-24 09:01 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx
> +                        <span className={styles.required}>*</span>
```suggestion
```

2023-09-24 09:01 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx
>                      <FormLabel className="label">
```suggestion
                    <FormLabel className="label" required>
```

2023-09-24 09:01 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx
>                      <FormLabel className="label">
```suggestion
                    <FormLabel className="label" required>
```

2023-09-24 09:01 UTC, Monyster commented on frontend/src/bundles/auth/components/auth-forms/sign-up-form/sign-up-form.tsx
> +                        <span className={styles.required}>*</span>
```suggestion
```

2023-09-25 08:39 UTC, merged