bt-582: [BUG] Validation schema differs from frontend to backend
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #609
Opened 2023-09-21 14:47 UTC by lavandosya

2023-09-22 14:11 UTC, anton-otroshchenko requested changes

2023-09-22 14:11 UTC, anton-otroshchenko commented on shared/src/bundles/user-details/validation-schemas/user-details-create.validation-schema.ts
> +        .regex(/^(www\.|http:\/\/|https:\/\/)[^.]+(\..+)+$/),
Create a variable for it

2023-09-24 09:16 UTC, Monyster requested changes

2023-09-24 09:16 UTC, Monyster commented on frontend/src/bundles/employer-onboarding/components/onboarding-form/onboarding-form.tsx
> +                            <span className={styles.requiredField}>*</span>
```suggestion
```

2023-09-24 09:16 UTC, Monyster commented on frontend/src/bundles/employer-onboarding/components/onboarding-form/onboarding-form.tsx
> +                            <span className={styles.requiredField}>*</span>
add require to FormLabel

2023-09-24 09:16 UTC, Monyster commented on frontend/src/bundles/employer-onboarding/enums/onboarding-form/onboarding-form.validation-rule.ts
>  };
```suggestion
} as const;
```

2023-09-24 09:16 UTC, Monyster commented on frontend/src/bundles/employer-onboarding/validation-schemas/onboarding-form/onboarding-form.validation-schema.ts
> +        .required()
```suggestion
        .trim().required()
```

2023-09-24 16:08 UTC, Monyster approved these changes

2023-09-25 08:40 UTC, nikita-remeslov approved these changes

2023-09-25 08:40 UTC, merged