bt-607: Talent onboarding screen change from step3 to step4
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #618
Opened 2023-09-21 18:10 UTC by anogire

2023-09-21 18:13 UTC, anogire commented
I had to change the frontend as well, but I tried not to break anything.
Please take a look at it.

2023-09-22 06:54 UTC, nikita-remeslov approved these changes

2023-09-22 07:57 UTC, nikita-remeslov requested changes
we decided to map data form backend to data that we need on frontend

2023-09-22 15:38 UTC, anogire commented
the new [PR](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/pull/646)

2023-09-22 15:38 UTC, closed without merging