bt-392: [BUG] Step 4 mobile bugs
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #630
Opened 2023-09-22 08:31 UTC by illia-dobro

![link](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/bcb74723-4ce3-4af8-809a-ccef42ea6e2a)

![plus](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/8fc5494d-325c-4cdc-893b-65431c256497)

![num](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/23e1b817-8570-4a9f-92a6-bdc86fb0e32b)

2023-09-22 12:14 UTC, katerynakostikova requested changes

2023-09-22 12:14 UTC, katerynakostikova commented on mobile/src/bundles/talent/enums/contacts-cv-step/cv-and-contacts-form-validation-message.enum.ts
> +        'Link format must be https://www.linkedin.com/in/',
as I remember PO asked us to skip this part https:// 
Ask QA team about it

2023-09-23 08:50 UTC, illia-dobro commented on mobile/src/bundles/talent/enums/contacts-cv-step/cv-and-contacts-form-validation-message.enum.ts
> +        'Link format must be https://www.linkedin.com/in/',
![qa](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/112649713/814f664d-fb9a-4bbe-913d-dea51f72756e)

2023-09-25 06:46 UTC, mskmee commented
Guess we should have validation schema and enum in the shared layer and use it front/mobile parts, just like we got them to another steps.
Maybe validation schema will be not the same, but enum will be the same anyway.

2023-09-25 09:20 UTC, katerynakostikova commented
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/392#issuecomment-1733123572

2023-09-27 09:17 UTC, katerynakostikova commented
See comment

2023-09-27 09:18 UTC, katerynakostikova commented
https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/392#issuecomment-1736931442

2023-09-27 13:54 UTC, mskmee commented
@illia-dobro

2023-09-27 15:28 UTC, katerynakostikova commented
Conflicts

2023-09-27 15:28 UTC, katerynakostikova approved these changes

2023-09-28 05:16 UTC, mskmee approved these changes

2023-09-28 07:11 UTC, merged