bt-638: Company talent hiring info
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #654
Opened 2023-09-24 00:37 UTC by savinaDaria

2023-09-25 21:37 UTC, nikita-remeslov commented
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/78347072/779743aa-c2f2-4f42-9ef8-2727864b6c78)
looks like our verification page should be Home page.
We can add another icon in the sidebar and call it Connection page

2023-09-25 21:37 UTC, nikita-remeslov commented
Also sidebar design. I think @JosuerBague did something with admin sidebar

2023-09-25 21:39 UTC, nikita-remeslov commented on backend/src/migrations/20230919162409_update_bsa_badges_table.ts
we should create new migrations to add those changes!

2023-09-25 21:40 UTC, nikita-remeslov requested changes

2023-09-25 21:40 UTC, nikita-remeslov commented on backend/src/migrations/20230907092959_update_files_table.ts
the same

2023-09-25 21:40 UTC, nikita-remeslov commented on backend/src/migrations/20230923202930_add_hiring_info_table.ts
> +const uuid = 'uuid_generate_v4()';
```suggestion
const UUID = 'uuid_generate_v4()';
```

2023-09-25 21:40 UTC, nikita-remeslov commented on backend/src/migrations/20230923202930_add_hiring_info_table.ts
> +const constraintName = 'hiring_info_pkey';
UPPERCASE

2023-09-25 21:40 UTC, nikita-remeslov commented on backend/src/migrations/20230923202930_add_hiring_info_table.ts
> +const TableName = {
enum

2023-09-25 21:40 UTC, nikita-remeslov commented on backend/src/migrations/20230923202930_add_hiring_info_table.ts
> +const ColumnName = {
enum

2023-09-26 01:22 UTC, savinaDaria commented
I also added Home component to handle navigation for different roles in Root

2023-09-26 12:41 UTC, nikita-remeslov approved these changes

2023-09-26 12:59 UTC, nika-sirak commented on backend/src/migrations/20230923202930_add_hiring_info_table.ts
> +            .primary(CONTRAINT_NAME);
```suggestion
            .primary({ constraintName: CONTRAINT_NAME });
```

2023-09-26 14:38 UTC, nika-sirak approved these changes

2023-09-26 14:39 UTC, merged