bt-530: add talent profile screen
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #666
Opened 2023-09-25 09:14 UTC by mskmee

<img width="194" alt="1" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/85788646/7166b43e-2a07-45ac-b7f2-5516a123745c">

2023-09-25 09:51 UTC, likeri29 commented on mobile/src/bundles/common/enums/navigation/talent-onboarding-screen-name.enum.ts
>      BSA_BADGES: 'BSA Badges',
Why the empty space?

2023-09-25 12:15 UTC, katerynakostikova commented
This screen header should match this UI 
<img width="480" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/103518438/e398d769-7065-4436-bc88-fc455662a298">

2023-09-25 12:19 UTC, katerynakostikova requested changes

2023-09-25 12:19 UTC, katerynakostikova commented on mobile/src/bundles/talent/components/profile-screen.profile-form/profile-screen-profile-form.tsx
> +const ProfileScreenProfileForm: React.FC<Properties> = ({
Can we reuse forms from onboarding?

2023-09-25 12:21 UTC, katerynakostikova commented on mobile/src/bundles/talent/components/profile-screen.profile-form/profile-screen-profile-form.tsx
> +const ProfileScreenProfileForm: React.FC<Properties> = ({
They have the same logic as step 1-4, on the each tab screen you just pass initial values to the forms

2023-09-27 07:43 UTC, katerynakostikova commented on mobile/src/bundles/talent/screens/profile-screen.contacts/profile-screen-contacts.tsx
> +};
If it is CV and contact form why we don't have it here?

2023-09-27 07:43 UTC, katerynakostikova commented on mobile/src/bundles/talent/screens/profile-screen.hirings/profile-screen-hirings.tsx
> +};
Let's hide this tab for now I think we'll now finish it till the demo

2023-09-27 13:14 UTC, katerynakostikova approved these changes

2023-09-27 13:14 UTC, katerynakostikova commented on mobile/src/bundles/talent/components/profile-tab-bar/profile-tab-bar.tsx
> +                </Pressable>
We already merged Logout button component

2023-09-27 13:17 UTC, illia-dobro approved these changes

2023-09-27 13:56 UTC, merged