bt-703: connect employer onboarding to api
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #718
Opened 2023-09-26 12:52 UTC by JosuerBague

Closes #703

2023-09-27 10:24 UTC, MaksymGavatuk requested changes

2023-09-27 10:24 UTC, MaksymGavatuk commented on frontend/src/bundles/talent-onboarding/store/actions.ts
> +    if (files.length > 0) {
Magic number

2023-09-27 10:24 UTC, MaksymGavatuk commented on frontend/src/bundles/employer-onboarding/store/actions.ts
> +            if (files.length > 0) {
The same

2023-09-27 12:13 UTC, nikita-remeslov requested changes
I think we dont need package-lock.json here

2023-09-27 20:16 UTC, nikita-remeslov approved these changes

2023-09-27 21:57 UTC, nika-sirak requested changes
Failed to run localy.

2023-09-27 22:48 UTC, JosuerBague commented
> Failed to run localy.
> <img alt="image" width="1109" src="https://user-images.githubusercontent.com/60103912/271125602-e1a33859-fc86-4a32-bf55-f3a8a34d9d29.png">

Fresh clone:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/afb2e397-bdb8-4c3d-8e20-feb456cb30cf)

My old clone:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/1d8ea969-1f97-4f74-8222-92dc3e077a29)


This is probably local to your npm @nika-sirak

2023-09-28 00:51 UTC, savinaDaria commented
@JosuerBague I have almost the same issue as @nika-sirak 
It should be connected with package-lock.json which is included in your PR, please exclude any changes to it so it won't be applied locally
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/58756139/7b5125c0-95f0-4848-a09c-7be0d2ae95b3)

2023-09-28 06:50 UTC, nikita-remeslov commented
I have updated package-lock.json in the development.
Just make 
`git checkout origin/development^ package-lock.json`

2023-09-28 07:29 UTC, nika-sirak approved these changes

2023-09-28 08:21 UTC, merged