bt-690:  Make changes in search-users endpoints
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #731
Opened 2023-09-26 19:40 UTC by MChornomaz

closes #690 
Add search_type column to user-details table in DB
add badges and hardskills to the response
show only candidate, which were approved by admin
change code in repository accorditng to task https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/605
change sorting by date from sorting by creation date to sorting by publish date
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/68593365/b5c550e0-e92a-491b-96e6-6a3c1f7867ff)

2023-09-26 21:49 UTC, MaksymGavatuk requested changes

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/user-details.service.ts
> +        });
Why we can't fetch users hard skills and badges using withGraphFetched method for example and in this case we join data using sql raw query and it much better than async map with Promise.all

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/helpers/apply-type-search-filter.ts
> +};
In this helper you use only payload.searchType, so you don't need to provide all payload to this helper

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/helpers/apply-profile-name-filter.ts
> +    }
The same provide only data which you will use

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/helpers/apply-location-filter.ts
> +    }
The same provide only data which you will use

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/helpers/apply-job-title-filter.ts
> +    }
The same provide only data which you will use

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/helpers/apply-hard-skills-filter.ts
> +    }
The same provide only data which you will use

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/helpers/apply-experience-filter.ts
> +};
The same provide only data which you will use

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/helpers/apply-english-level-filter.ts
> +};
The same provide only data which you will use

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/helpers/apply-employment-type-filter.ts
> +    payload: UserDetailsSearchUsersRequestDto,
The same provide only data which you will use

2023-09-26 21:49 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/apply-filters/apply-filters.ts
> +const applyFilters = (
```suggestion
const applyAllFilters = (
```

2023-09-27 18:12 UTC, MaksymGavatuk requested changes

2023-09-27 18:12 UTC, MaksymGavatuk commented on frontend/src/bundles/talent-onboarding/types/candidate-profile/candidate-profile.ts
> +    hardSkills?: { id: string; name: string };
Type please

2023-09-27 18:12 UTC, MaksymGavatuk commented on frontend/src/bundles/search-candidates/types/seacrh-candidate-dto/seacrh-candidate-dto.ts
> +    }[];
Type

2023-09-27 18:12 UTC, MaksymGavatuk commented on frontend/src/bundles/search-candidates/store/actions.ts
> +            })) as SeacrhCandidateDto;
Why you need to use casting ?

2023-09-27 18:12 UTC, MaksymGavatuk commented on frontend/src/bundles/candidate-details/components/candidate-profile/candidate-profile.tsx
> +            : hardskillsLabels,
Why use casting ?

2023-09-27 18:12 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/user-details.repository.ts
> +            .withGraphJoined('[user, talentHardSkills]')
Why do you use separate withGraphJoined, if you need both of them use just .withGraphJoined('[user, talentHardSkills, talentBadges.[badge]]');

2023-09-27 18:12 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/user-details.model.ts
> +    public 'badges'?: TalentBadgeEntity;
When you use graph fetching this type should be TalentBadgeModel

2023-09-27 18:12 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/user-details.entity.ts
> +    private 'badges'?: UserDetailsResponseBadgeDto[] | null;
We don't need this field in entity

2023-09-27 18:12 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/user-details.entity.ts
> +    private 'hardSkills'?: HardSkillsEntity[];
We don't need this field in entity

2023-09-27 18:12 UTC, MaksymGavatuk commented on backend/src/bundles/user-details/helpers/map-search-users-response-badges.ts
> +    const formattedBadges: (UserDetailsResponseBadgeDto | undefined)[] =
Why we use undefined ?

2023-09-27 18:12 UTC, MaksymGavatuk commented on backend/src/bundles/talent-badges/talent-badge.model.ts
> +    public 'badge'?: BSABadgeEntity;
model

2023-09-27 18:12 UTC, MaksymGavatuk commented on backend/src/bundles/talent-badges/talent-badge.entity.ts
> +    private 'badge'?: BSABadgeEntity | null;
We don't need this in enitity

2023-09-27 18:12 UTC, MaksymGavatuk commented on backend/src/bundles/bsa-badges/bsa-badges.entity.ts
> +    public 'maxScore': number;
Why we change it to public ?

2023-09-28 00:02 UTC, savinaDaria commented
merged with #763 to apply&test proper candidate page handling

2023-09-28 19:41 UTC, nikita-remeslov approved these changes

2023-09-28 19:41 UTC, merged