bt-742: add empty chat page placeholder
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #749
Opened 2023-09-27 13:41 UTC by JosuerBague

Add placeholder for empty chat list state.

2023-09-27 19:13 UTC, vladjsp commented
Clean code but found some UI issues actually not directly related to this task but still.
1. Chrome - Empty chats list and messages list have right scroll. Not critical, but it looks a bit out of place.
2. Message 'Nothing was found' looks strange for an empty chats list.
3. Personal.  font-size - clamp(2vw, var(--font-size-h2), 5vw); looks a bit huge on 1920x1080 15.9" screen. 
![kdfjghdfg](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/82158f8e-3be0-4ac7-bde2-f393ff928ca4)

2023-09-27 19:30 UTC, nikita-remeslov requested changes
Just remove all chat and render placeholder

2023-09-28 08:05 UTC, JosuerBague commented
Desktop
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/c77247b5-87dd-47b2-87ec-4f8c130b158b)

Tablet:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/e893789e-104b-4564-b8e1-f4fe852cb989)

Mobile:
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/90120572/b75bb19d-62ec-4444-8d3e-5ca195cedd28)

2023-09-28 08:20 UTC, nikita-remeslov approved these changes

2023-09-28 08:21 UTC, vladjsp approved these changes

2023-09-28 08:25 UTC, merged