bt-746: Quality Criteria
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #760
Opened 2023-09-27 16:18 UTC by nika-sirak

2023-09-27 16:32 UTC, savinaDaria approved these changes

2023-09-27 19:47 UTC, MaksymGavatuk approved these changes

2023-09-27 20:12 UTC, nikita-remeslov requested changes

2023-09-27 20:12 UTC, nikita-remeslov commented on shared/src/bundles/user-details/enums/experience-years-list.enum.ts
> +    const experienceYearsEnum: Record<string, number> = {};
enum is data type

2023-09-27 20:12 UTC, nikita-remeslov commented on shared/src/helpers/talent-onboarding/create-number-range.ts
> +    const numbers = [];
```suggestion
    const ranges = [];
```

2023-09-27 21:10 UTC, nika-sirak commented on shared/src/bundles/user-details/enums/experience-years-list.enum.ts
> +    const experienceYearsEnum: Record<string, number> = {};
Renamed

2023-09-28 06:43 UTC, nikita-remeslov approved these changes

2023-09-28 06:43 UTC, merged