bt-558: Add company page
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #762
Opened 2023-09-27 17:45 UTC by ptarho

I created a new branch for this ticket because, after some changes in the development branch, I spent nearly 2 hours trying to resolve conflicts, but unfortunately, I couldn't resolve them.
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/67747035/b343a8ea-a31a-485f-b302-5f71bd59b4bc)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/67747035/5171995d-af97-473d-9419-17aa77402924)

2023-09-27 19:49 UTC, MaksymGavatuk requested changes

2023-09-27 19:49 UTC, MaksymGavatuk commented on frontend/src/bundles/employer/pages/company/company-page.tsx
> +        // }
Remove comment

2023-09-28 08:36 UTC, ptarho commented on frontend/src/bundles/employer/pages/company/company-page.tsx
> +        // }
Fixed

2023-09-28 14:34 UTC, nikita-remeslov approved these changes

2023-09-28 14:34 UTC, merged