bt-774: Skills and Projects tab is displayed stretched when too many skills are added
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #780
Opened 2023-09-28 15:10 UTC by vladjsp

closes https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/issues/774
![Screenshot 2023-09-28 at 18-08-52 BSA Talents](https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/118971905/01ade39d-08e9-4786-880b-31101d390647)

2023-09-28 18:52 UTC, JemiJe commented on frontend/src/bundles/profile-cabinet/pages/styles.module.scss
> +    width: 560px;
maybe move it to variables n assets and the same pages can use this width in similar potential bugs?

2023-09-28 19:55 UTC, nikita-remeslov requested changes

2023-09-28 19:55 UTC, nikita-remeslov commented on frontend/src/bundles/profile-cabinet/pages/styles.module.scss
> +    width: 560px;
```suggestion
    width: 100%;
```

2023-09-28 20:39 UTC, vladjsp commented on frontend/src/bundles/profile-cabinet/pages/styles.module.scss
> +    width: 560px;
fixed

2023-09-28 21:01 UTC, anton-otroshchenko approved these changes

2023-09-29 06:44 UTC, nikita-remeslov approved these changes

2023-09-29 06:44 UTC, merged