bt-30: Create Bottom tabs navigation
BinaryStudioAcademy/bsa-2023-bsa-talents pull request #83
Opened 2023-08-23 14:16 UTC by anogire

I have made a separate AuthNavigation, which should include all pages for authorized users (maybe there will be more, not just those in the bottom tab).
So, app.tsx will probably have a switch to AuthNavigation or RootNavigation.

2023-08-23 14:59 UTC, likeri29 commented
I thought that you needed Icons for buttons and they are not on the development branch yet.

2023-08-23 15:00 UTC, anogire commented
yes, i am waiting for icons.

2023-08-23 19:52 UTC, nikita-remeslov approved these changes
Looks good to me, but we need icons

2023-08-24 06:30 UTC, katerynakostikova commented
So, I'd like to change the structure a bit. We should have a RootNavigator component, which will work like this:
```
               <RootStack.Navigator>
			{!isSignedIn ? (
						<RootStack.Screen
							name={AUTH_ROOT_ROUTE} // This Navigator should have auth-related screens 
							component={AuthNavigator}
						/>
					) : 
                                                   // This one will have bottom tabs 
						<RootStack.Screen name={MAIN_ROOT_ROUTE} component={MainRootNavigator} />
				</RootStack.Group>
			)}
		</RootStack.Navigator>
```
For now, you can manually change the value of `isSignedIn` 

Also, please provide screenshots of created navigation (with icons when they'll be merged)

2023-08-24 06:31 UTC, katerynakostikova requested changes

2023-08-24 06:31 UTC, katerynakostikova commented on mobile/src/app/app.tsx
> +                    <AuthNavigation />
All related to my comment manipulations should be in RootNavigation component, in App we just leave RootNavigation

2023-08-24 10:20 UTC, anogire commented
1. If I understand correctly, we will also need MainNavigator for Drawer navigation.

2. Not sure if I need to separate generateTabBarIcon ...

3. If isSignedIn == true
<img width="393" alt="Screenshot 2023-08-24 at 13 11 31" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/48a6284a-0d4a-47d2-b578-539155da0fd8">

<img width="393" alt="Screenshot 2023-08-24 at 13 11 37" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/523a190a-295d-4908-85de-87841b00ba22">

<img width="393" alt="Screenshot 2023-08-24 at 13 11 42" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/00c436fd-38ad-4235-bd07-ccd448fdfa72">


4.   If isSignedIn == false
<img width="393" alt="Screenshot 2023-08-24 at 13 15 40" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/e1c6b387-f626-4570-9e7e-86a6786d1e4f">

2023-08-24 11:02 UTC, mskmee approved these changes
Looks good, as for me)

2023-08-24 11:11 UTC, anogire commented
Or, is Drawer navigation our "Sign Up page" that should be without bottom navigation?
Then, probably, a separate BottomTabNavigator is unnecessary and I can move it to the MainNavigator.

2023-08-25 06:21 UTC, katerynakostikova commented on mobile/src/bundles/common/enums/navigation/root-screen-name.enum.ts
> +    MAIN_ROOT_ROUTE: 'Main root route',
```suggestion
    AUTH_ROOT_ROUTE: 'Auth Root Route',
    MAIN_ROOT_ROUTE: 'Main Root Route',
```

2023-08-25 06:21 UTC, katerynakostikova commented on mobile/src/navigations/bottom-tab/bottom-tab.tsx
> +                }}
```suggestion
                options={{
                    tabBarIcon: ({ color }) =>
                       <Icon />
                }}
```

2023-08-25 06:21 UTC, katerynakostikova commented on mobile/src/navigations/bottom-tab/generate-tab-bar-icon.tsx
> +};
You can just return icon component in navigator

2023-08-25 06:21 UTC, katerynakostikova commented on mobile/src/navigations/bottom-tab/styles.ts
> +        height: 95,
Why 95?

2023-08-25 06:21 UTC, katerynakostikova commented on mobile/src/navigations/main-navigator/main-navigator.tsx
We can remove this main navigator

2023-08-25 06:21 UTC, katerynakostikova commented on mobile/src/navigations/root/root.tsx
> +                    component={MainNavigator}
```suggestion
                    component={MainBottomTabNavigator}
```

2023-08-25 07:04 UTC, anogire commented on mobile/src/navigations/bottom-tab/styles.ts
> +        height: 95,
Yes, in Figma it is 97 ...

2023-08-25 07:37 UTC, katerynakostikova approved these changes

2023-08-25 07:37 UTC, katerynakostikova commented on mobile/src/navigations/main-bottom-tab/styles.ts
> +        height: 97,
```suggestion
```
Let's make it 50 or just add some paddings. Let's avoid using some magical numbers

2023-08-25 07:38 UTC, katerynakostikova commented on mobile/src/navigations/main-bottom-tab/styles.ts
> +        height: 97,
For example on my phone 97 height looks too big, because I also have android bottom menu

2023-08-25 08:12 UTC, anogire commented
Padding does not work correctly, only paddingTop or using `<View><Icon></View>`
So I suggest still using height

This is for 50
<img width="393" alt="Screenshot 2023-08-25 at 11 08 08" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/71677f2e-50d6-43a6-adf5-16352efc41b3">


This is for 60
<img width="393" alt="Screenshot 2023-08-25 at 11 08 46" src="https://github.com/BinaryStudioAcademy/bsa-2023-bsa-talents/assets/70234990/53bb131a-70f1-40e5-a740-8d1a248db172">

2023-08-25 08:24 UTC, katerynakostikova commented
Let's use 60

2023-08-25 08:24 UTC, katerynakostikova approved these changes

2023-08-25 08:28 UTC, anogire commented
I also like it better

2023-08-25 08:29 UTC, merged